name: Cron Example

on:
  schedule:
    - cron:  "0 5 * * *" # Run daily at 05:00 UTC
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cron-example

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
