name: Cron Start
on:
  workflow_dispatch:
jobs:
  run-integration-test-Alexs:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cron-example
    steps:
      - uses: actions/checkout@v2
      # Setup Nodejs
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # Install Yarn
      - name: Intall Yarn
        run: npm install --global yarn
      # Install libraries
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Run test
      - name: Run test
        run: yarn test